services:
  bot:
    image: ${IMAGE:-ghcr.io/vitorhugo-dotnet/framerelay-discord-bot:latest}
    container_name: framerelay-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - infra_network

networks:
  infra_network:
    external: true
    name: infra_network
